version: "3.8"

services:
  shrine-redis:
    image: redis/redis-stack-server
    container_name: shrine-redis
    entrypoint: redis-stack-shrine --requirepass 123  --appendonly yes
    ports:
      - "6379:6379"
    networks:
      - shrine-net

networks:
  shrine-net:
    name: shrine-net
    driver: bridge
