version: "3.8"

services:
  app:
    build: .
    container_name: shrine
    ports:
      - "3000:3000"
    networks:
      - shrine-net
    depends_on:
      - shrine-redis
  shrine-redis:
    image: redis:7.2.4-alpine3.19
    container_name: shrine-redis
    entrypoint: redis-server --requirepass 123  --appendonly yes
    ports:
      - "6379:6379"
    networks:
      - shrine-net

networks:
  shrine-net:
    name: shrine-net
    driver: bridge
