version: "3.8"

services:
  app:
    build: .
    container_name: shrine
    ports:
      - "3000:3000"
    networks:
      - shrine-net
  shrine-redis:
    image: redis/redis-stack-server
    container_name: shrine-redis
    entrypoint: redis-stack-server --requirepass 123  --appendonly yes
    ports:
      - "6379:6379"
    networks:
      - shrine-net

networks:
  shrine-net:
    name: shrine-net
    driver: bridge
